name: Checkmarx Scan

on:
  push:
    branches:
      - *
  schedule:
    - cron: '0 10 * * *'  # Every day at 10:00 UTC
  workflow_dispatch: 

permissions:
  contents: read
  security-events: write

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        
      - name: Run Checkmarx Scan
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://deu.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          cx_tenant: accuknox-nfr
          scan_params: --report-format sarif --output-path .

      - name: Upload SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cx_result.sarif
          
      - name: Upload SARIF file 
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sarif-results-push
          path: cx_result.sarif
          if-no-files-found: warn
          retention-days: 30

#       - name: Send Checkmarx Result to AccuKnox SaaS Dev Env
#         uses: accuknox/checkmarx-accuknox-action@v1.0.0
#         with:
#           api_key: ${{ secrets.CX_API_KEY }}
#           project_name: "AyushAggarwal1/gst-bill"
#           accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
#           tenant_id: ${{ secrets.TENANT_ID }}
#           ak_token: ${{ secrets.ACCUKNOX_TOKEN }}
#           label_id: "ayushcicd"
#           upload_artifact: true
