name: Supabase DB Backup

on:
  # push:
  #   branches:
  #     - dev
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 AM
  workflow_dispatch:  # Allows manual trigger

jobs:
  db-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Make backup script executable
        run: chmod +x db-backup.sh

      - name: Run Database Backup script
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./db-backup.sh
